### PR TITLE
update

### PR DESCRIPTION
**Pull request by JCherryhomes**
added a check in the Runtime parser to return null when no number is in the json string.
Added function for retrieving a movie's full cast by the movie id.

### CODE REVIEW

**Comment by sergiotapia** [comment]
Hey nakor, thanks for contributing! :) I made a lot of changes to how the Parser.cs class is organized, can you get my new changes and see it? 

Any suggestions on where we could improve next? I've addressed a lot of the clutter and organized the parsing methods into easily maintainable methods.

**Comment by JCherryhomes** [comment]
I updated my version to match yours before I made the last updates. I like having the individual parsers, nice addition.

**Comment by JCherryhomes** [comment]
I think if you click the "Network" link above you can see the last time I merged with your project. Did you make more changes to the parser.cs since then?

**Comment by JCherryhomes** [comment]
I've also added an MVC website example project to mine, but haven't committed it yet.

**Pull request closed without merging**
